### ISSUE TITLE
Feature Suggestion: Prompt for missing fonts on Penpot import, not Figma export

### ISSUE THREAD

**Issue by ryanbreen** [penpot/penpot-exporter-figma-plugin#231]
I'm wondering if a better workflow for exporting from Figma and importing to Penpot is to handle missing fonts at import time rather than forcing the user to pair up a Penpot font ID at export time.

Here's the thinking:

-  It's clunky for the user to need to dig up the matching font id on the Penpot side and tell Figma, and it's error-prone because they might paste the wrong font id to the wrong place.
- We get a font family name on the Figma side, so we have all the information we need to look for matches during input.
- On import, we check for matches and automatically assign them.  For any font families that don't exist on the Penpot side, we prompt the user to upload the font file.

(This is at least as much a Penpot feature suggestion as an exporter feature suggestion, so I'll submit a modified version over there as well.)

**Comment by Cenadros** [comment]
Hi there @ryanbreen. Actually I have some good news about this.

Actually penpot did an update where they correctly match the fonts based in the font-name and font-family rather than the ids. So, as long as you have your custom fonts loaded in penpot, you won't need to fill the ids in the exporter. (This will work at the moment in our current version of the plugin)

In a future update we'll be removing that functionality from the plugin and just letting the user know that the fonts must be loaded in penpot.

Closing this issue since this is already addressed in penpot and we have it in our future plans ;)

**Comment by ryanbreen** [comment]
You guys are crazy, amazing!
