### ISSUE TITLE
Bug: Exported Figma stroke components flip vertically and shifted down

### ISSUE THREAD

**Issue by EnriqueTMT** [penpot/penpot-exporter-figma-plugin#233]
# Problem

Some components in Figma get transformed in PenPot after using the penpot-exporter-figma-plugin. The transformation seems to be a vertical mirror or flip and a shift or translation down. It could also be a vertical mirror along the components x-axis.
It's hard to tell what the root of the bug, but in one of the samples (attached to this issue ticket), undoing the horizontal mirror or flip with a second horizontal flip fixes it. Also, applying a second flip or mirror (doesn't matter if it's horizontal or vertical) seems to fix the issue. My guess undoing the transformation, or overriding it fixes it.

Here is what it looks like in PenPot (after export from Figma) on the left and what it's supposed to look like (as an image).
![image](https://github.com/user-attachments/assets/e91ca310-7c34-488e-bdb5-65caec8ea1a3)

# Current Solutions

- Apply a horizontal flip. Works if you don't need to flip the component.
- Apply two mirrors or flips. Only works if the component in question has symmetry. Text or unique objects will likely be upside down.
- Rotate your component or object by anything less than 360 degrees (worked with 90 and 180 degrees). Works if your component has that flexibility.
- After using the plugin, export the selected areas that get bugged into SVGs in Figma, delete the bugged components in PenPot, and paste the SVG file. Acceptable if you don't have too many bugs components.
- Fix it in PenPot.

# Developer Solutions

I don't know. I'm still unsure about the root of the problem.

# Samples & Attached Files

Attached is the .fig file from Figma so that you can use it for testing.
It seems I cannot attach a .fig file. So I'll put it in a zip folder.
[Test file of Mirror Export Bug.zip](https://github.com/user-attachments/files/17512792/Test.file.of.Mirror.Export.Bug.zip)

I tested this bug for a bit to see if I could figure it out for the PenPot team, but didn't find out much.
Inside you'll find the following:
- My notes on some observations.
- Two sets of original files and bugged files along with their attempted solutions.
- Extra bugged samples to try out solutions on.

**Comment by Cenadros** [comment]
Hi there @EnriqueTMT ,

First of all thank you for the tremendous effort you have put into assembling such a test document. It's been a huge help.

We've been tracking this issue and opened a PR #236 to fix this issue. Apparently the issue happened because we were not taking into account some transformations. Flipping a shape horizontally or vertically makes some weird changes in the shape properties when retrieving them from the Figma API.

We were assuming that if a shape is not rotated, there is no transformation, which is not the case.

This is fixed in the PR and will be implemented in the next release.

Again, thank you for all your efforts.
