### ISSUE TITLE
Unable to load error

### ISSUE THREAD

**Issue by abhiXII** [penpot/penpot-exporter-figma-plugin#24]
Hi!
When I try to run the plugin it shows me this error 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/124244361/225983250-31e32107-be8b-4630-93f3-3ad5b0ce13a2.png">

Here's how i'm trying to use it
<img width="733" alt="image" src="https://user-images.githubusercontent.com/124244361/225983314-02a80915-c53a-470f-85bc-352b4ad791b3.png">

**Comment by pabloalba** [comment]
Hi! Does it happens with any file, or with a specific one? Can you try to execute it on a simple file with a rectangle, for example?

**Comment by AnaelleMADY** [comment]
Hello, I still have the error even with a very simple shape.

**Comment by abhiXII** [comment]
Hi @pabloalba sorry I dropped the ball on this. but like @AnaelleMADY said, I'm facing issues with exporting simple shape too. My error now is that when I hit export button, nothing happens.
<img width="353" alt="image" src="https://github.com/penpot/penpot-exporter-figma-plugin/assets/124244361/03ce2ab0-7331-49bc-8d24-cea2657cb265">
<img width="798" alt="image" src="https://github.com/penpot/penpot-exporter-figma-plugin/assets/124244361/d2b8b156-7595-4e4a-8e0c-30e06b77917f">

**Comment by jordisala1991** [comment]
Hi! We are continuing the development of this plugin. We did a complete refactor of the structure of the code and fixed several bugs on different topics.

Since the code is quite different, can you try again with the main branch?

For now I am closing since we didn't saw similar errors on our side, but if you see the same problem, please answer here and I will reopen.
