### ISSUE TITLE
i've published the plugin to Figma community

### ISSUE THREAD

**Issue by micahchoo** [penpot/penpot-exporter-figma-plugin#25]
https://www.figma.com/community/plugin/1219369440655168734

Let me know if any one from the Kaleidos' Team or contributors  would like update privileges or be added as a creator

**Comment by v3ss0n** [comment]
It dosen't work .

**Comment by micahchoo** [comment]
What part didn't work for you?

**Comment by v3ss0n** [comment]
it won't export/run at all. anyways i have stopped using penpot too due to being very resoure intensive and slow.

**Comment by jordisala1991** [comment]
Hey @micahchoo , we have started a collaboration (Runroom) with Penpot to continue the development. We didn't saw your offering about transfering the creator rights to Kaleidos or contributors, so we published again the repository.

Here you can see it: https://www.figma.com/community/plugin/1362760353975083275/penpot-exporter

Since your publication is older and has already some installments on figma, would you mind transferring the ownership? The idea would be to only have one version published so we don't confuse our users.

Thanks!

**Comment by jordisala1991** [comment]
Thank you @micahchoo , can you invite software@runroom.com? We can continue from there inviting the rest of the team.

**Comment by micahchoo** [comment]
It doesn't show it as a community account?

**Comment by jordisala1991** [comment]
This is our community profile: https://www.figma.com/@runroom

**Comment by jordisala1991** [comment]
Hi @micahchoo , did you had time to transfer the ownership of the plugin?

**Comment by micahchoo** [comment]
I have sent an invite for update permissions, but am still unable to add as owner. The runroom profile doesn't pop up at all

**Comment by jordisala1991** [comment]
This is solved, we already swapped ownership. Thank you @micahchoo 🙏
