### ISSUE TITLE
vector support > svg

### ISSUE THREAD

**Issue by manfredsteger** [penpot/penpot-exporter-figma-plugin#26]
Hello, I find the plugin very helpful so far. However, in order to efficiently transfer more complex layouts, the embedded vectors such as icons/graphics SVG would also need to be exported. This would allow wireframes to be fully transferred already.

**Comment by madalenapmelo-kp** [comment]
Hi @manfredsteger,

Thanks for the feedback! I just wanted to let you know that we have shared the baseline project for this plugin for the community to continue it - we have explained our approach to the penpot-exporter-figma-plugin in this [community post](https://community.penpot.app/t/figma-file-importer/1684).

We are not actively maintaining or resolving issues on this plugin, but we encourage you to contribute if and where you can :slightly_smiling_face:

**Comment by jordisala1991** [comment]
This is already implemented after merging this PR: 

https://github.com/penpot/penpot-exporter-figma-plugin/pull/37
https://github.com/penpot/penpot-exporter-figma-plugin/pull/35

We did a restart of the development of the plugin. Please take a look at the main branch and try it if you have time. Any help testing it is very welcome 😄 

You can open other Issues if you find some problems with the current version.

I will let you the backlog also linked here because not everything is covered: https://github.com/orgs/penpot/projects/1

Closing this one for now.
