### ISSUE TITLE
Symbol Unwrapping failure during initialization

### ISSUE THREAD

**Issue by micenest** [penpot/penpot-exporter-figma-plugin#6]
Hello! I am currently attempting to use this project to import some of my most important files in Figma and i'm still getting the same error as issue #2 (albeit, from what it looks like - different causes?), even after the latest #3 PR that worked around the multi-glyph typography issue.

I am using the latest commit as of this message ( 881a13f ) and no noticeable warnings were given during the build process itself.

Exception goes as follows: 
```js
Error: in postMessage: Cannot unwrap symbol
    at <anonymous> (PLUGIN_3_SOURCE:91)
    at <anonymous> (PLUGIN_3_SOURCE:101)
    at call (native)
    at <eval> (PLUGIN_3_SOURCE:105)
``` 

Thanks for making this! Hope to hear more about this issue soon.

**Comment by pabloalba** [comment]
Hi @micenest 

This plugin is in a very early stage, so it's expected that it won't work on a lot of files. I'd love to check the error if you can give me a file sample that throws it. If it is confidential and you can't put it here, you can send it to support@penpot.app.

Thank you!

**Comment by pabloalba** [comment]
Hi!
I've found the problem. It was because we didn't check for [figma.mixed](https://www.figma.com/plugin-docs/api/properties/figma-mixed/) fills.

It's solved now, and the snippet doesn't throw any errors. The result is very bad because the plugin doesn't support vectors yet. But the error is gone, so that's something, I guess...
