### ISSUE TITLE
import faill from figma to penepot

### ISSUE THREAD

**Issue by xBLACKICEx** [penpot/penpot-exporter-figma-plugin#87]
Is this plugin unable to import slightly more complex figma projects?

For example, I tried to import this [figma](https://www.figma.com/file/muqfIH4DSMbG3PKF7MhgG0/Fitnest---Fitness-App-UI-Kit-by-Pixel-True-(Community)?type=design&node-id=206-281&mode=design&t=q93FMworwvhp52ty-0) project and it kept failing.
![图片](https://github.com/penpot/penpot-exporter-figma-plugin/assets/51036094/2b725ec4-8f76-4444-bd9b-478de77e6955)
![图片](https://github.com/penpot/penpot-exporter-figma-plugin/assets/51036094/3d319a55-96d5-401a-a4ca-e6fbe1afb340)
![图片](https://github.com/penpot/penpot-exporter-figma-plugin/assets/51036094/49a229c0-9f4c-41aa-8584-7ae492f24f60)

Version: v0.2.2 (Version 7)
OS: windows 11

**Comment by Cenadros** [comment]
Hi there @xBLACKICEx,

The project is currently in development since we're rebuilding it from scratch. Currently complex projects containing images for example will not work but we're working on it. I invite you to check our [https://github.com/orgs/penpot/projects/1/views/3](roadmap) where you'll see an estimation on when we're planning to give support for several functionalities.

Also thank you for providing the figma project you're being having issues with since it will be really useful for our testing as we continue developing.

Keep in touch for future releases and we'll let you know in this issue when it's fixed.

**Comment by Cenadros** [comment]
Hi there @xBLACKICEx,

We've just made a release of the plugin that fixes this issue. Please keep in mind that even if the design is imported into penpot, we currently don't support some things like components, boolean groups, etc.

We keep updating our [roadmap](https://github.com/orgs/penpot/projects/1/views/3) where you can see the development progress.

Closing this issue and thanks for your feedback!
